### ISSUE TITLE
can't start on Mac OSX 10.11.6 python 3.6.0a4

### ISSUE THREAD

**Issue by steros** [metadirective/GPicSync#7]
I'm not sure if it is even possible to run your great software on mac but I read it is possible.
Unfortunately I'm getting this error:

> $ python gpicsync-GUI.py
> Traceback (most recent call last):
>   File "gpicsync-GUI.py", line 29, in <module>
>     from unidecode import unidecode # unicode to ascii (see issue 117 regarding Python 2.x and command line to exiftool containing unicode)
> ImportError: No module named unidecode

**Comment by metadirective** [comment]
Someone made a Mac port many years ago but unfortunately it hasn't been maintained after; very unlikely to work on current OSX. Sorry about that.

**Comment by steros** [comment]
no prob :)

**Comment by mlucool** [comment]
As an fyi, you can get this running on a mac for the CLI version from source. I struggled/gave up on the GUI version (you need wxPython and I could not get that to place nice with anaconda).

You'll need to install at least ```unidecode``` (via pip or whatever else you choose) and also install [exiftool](http://www.sno.phy.queensu.ca/~phil/exiftool/). From there the CLI did seem to work.
